### ISSUE TITLE
该项目是否不支持i686

### ISSUE THREAD

**Issue by rong-xiaoli** [kiliokuara/magic-signer-guide#2]
以如下参数运行Docker：
`docker run -d --restart=always -e SERVER_IDENTITY_KEY=vivo50 -e AUTH_KEY=kfc -e PORT=8888 -p 8888:8888  --log-opt mode=non-blocking --log-opt max-buffer-size=4m  -v /home/vivo50/serverData:/app/serverData -v /home/vivo50/testbot:/app/testbot kiliokuara/vivo50`
相比于README中给出的命令缺少`--rm`是因为：#1 
![心情复杂.jpg](https://github.com/kiliokuara/magic-signer-guide/assets/58361774/dd66ab8c-f14e-42b1-bb46-438b61686285)
lscpu 运行结果：
![image](https://github.com/kiliokuara/magic-signer-guide/assets/58361774/222e4149-e626-4082-aae7-834917fb3059)
但是我疑惑的地方在于，按理来讲这颗CPU可以执行这个吧？

**Comment by kiliokuara** [comment]
此项目只支持64位系统，你应该问搜索引擎

**Comment by rong-xiaoli** [comment]
got it，可以close了![流泪](https://user-images.githubusercontent.com/58361774/252417008-6286fe86-7c34-426d-aef1-c17ef05253a2.jpeg)
